//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogApp.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int DogId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> FinishedAt { get; set; }
        public Nullable<System.DateTime> SentAt { get; set; }
        public Nullable<System.DateTime> DeliveredAt { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Neck { get; set; }
        public Nullable<decimal> Back { get; set; }
        public Nullable<decimal> Chest { get; set; }
        public Nullable<decimal> Waist { get; set; }
        public Nullable<decimal> FrontLegs { get; set; }
        public Nullable<decimal> BackLegs { get; set; }
        public string Note { get; set; }
    
        public virtual Dog Dog { get; set; }
        public virtual Person Person { get; set; }
    }
}
